### PR TITLE
Better checkpoint diagnostics

### LINKED ISSUE #67: Better diagnostics for Checkpoint.flag
If I write a test which uses multiple checkpoints then if one of them doesn't have `flag()` called I get "java.util.concurrent.TimeoutException: The test execution timed out. Make sure your asynchronous code includes calls to either VertxTestContext#completeNow(), VertxTestContext#failNow() or Checkpoint#flag()". In y particular case I know I have all the necessary `flag()`s in the code, and I know that one of them is not getting called, but I've no idea which one, which makes it harder to debug.

It would be much more helpful if it told me which checkpoint hadn't been flagged. For example this could be either in the form of a stacktrace from the point at which `checkpoint()` was called, or or by having the option to name checkpoints.

### PR DESCRIPTION
**Pull request by jponge**
Provide a diagnostic of unsatisfied checkpoints call sites

This inspects the call stack when a checkpoint is being created to find the most likely call site in user code.

Fixes #67

### CODE REVIEW

File: vertx-junit5/src/main/java/io/vertx/junit5/CountingCheckpoint.java [hunk 1]
```diff
@@ -47,11 +48,22 @@ private CountingCheckpoint(Consumer<Checkpoint> satisfactionTrigger, Consumer<Th
...
       throw new IllegalArgumentException("A checkpoint needs at least 1 pass");
     }
+    this.creationCallSite = findCallSite();
     this.satisfactionTrigger = satisfactionTrigger;
     this.overuseTrigger = overuseTrigger;
     this.requiredNumberOfPasses = requiredNumberOfPasses;
   }
 
+  private StackTraceElement findCallSite() {
+    StackTraceElement[] stackTrace = new Exception().getStackTrace();
```
Comment (slinkydeveloper) [inline vertx-junit5/src/main/java/io/vertx/junit5/CountingCheckpoint.java]: Why this statement more than https://github.com/vert-x3/vertx-junit5/blob/master/vertx-junit5-web-client/src/main/java/io/vertx/junit5/web/TestRequest.java#L289 `Thread.currentThread().getStackTrace()`? Any difference?

File: vertx-junit5/src/main/java/io/vertx/junit5/VertxTestContext.java [hunk 2]
```diff
@@ -79,6 +81,19 @@ public synchronized boolean completed() {
     return !failed() && releaseLatch.getCount() == 0;
   }
 
+  /**
+   * Gives the call sites of all unsatisifed checkpoints.
+   *
+   * @return a list of {@link StackTraceElement} references pointing to the unsatisfied checkpoint call sites.
+   */
+  public List<StackTraceElement> unsatisfiedCheckpointCallSites() {
```
Comment (tombentley) [inline vertx-junit5/src/main/java/io/vertx/junit5/VertxTestContext.java]: If the list order is important when the doc should probably explain what it is. If not, then why is the return type a list?

File: vertx-junit5/src/main/java/io/vertx/junit5/CountingCheckpoint.java (hunk 1 above)
Comment (jponge) [reply vertx-junit5/src/main/java/io/vertx/junit5/CountingCheckpoint.java]: The goal here is to just pin-point the flag creation line in the code. The full stacktrace is not so much relevant since there is no execution context of interest, you really just want to identify which checkpoints have been left unsatisfied.

File: vertx-junit5/src/main/java/io/vertx/junit5/VertxTestContext.java (hunk 2 above)
Comment (jponge) [reply vertx-junit5/src/main/java/io/vertx/junit5/VertxTestContext.java]: It's a list of `StackTraceElement` where each element points to the line where an unsatisfied flag has been created. The order does not matter, what you really want is some diagnosis like:

```
-> Flag in Foo.java at line 123 was not satisfied
-> Flag in Foo.java at line 456 was not satisfied
```

API implementers may use this API, but users will really just see the diagnosis message in logs through `VertxExtension`.

**Comment by jponge** [comment]
Waiting from @tombentley @slinkydeveloper before I merge

File: vertx-junit5/src/main/java/io/vertx/junit5/VertxTestContext.java (hunk 2 above)
Comment (tombentley) [reply vertx-junit5/src/main/java/io/vertx/junit5/VertxTestContext.java]: Personally I would use `Collection` or `Iterable`, but I guess `List` is fine.

**Comment by jponge** [comment]
Or `Set`? :-)
